[tool.poetry]
name = "tcc"
version = "0.1.0"
description = "Meu TCC S2"
authors = ["Rich <richelton14@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
PyPDF2 = "^1.26.0"
PyMuPDF = "^1.19.2"
pdfminer3 = "^2018.12.3"
"pdfminer.six" = "^20211012"
spacy = "^3.2.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.11b1", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
